export const clients = [
  {
    id: 1,
    email: "admin1@email.com",
    password: "pass123",
    client: "Artisan",
    name: [
      {
        id: 11,
        name: "Alice Patricia",
        link: "https://datastudio.google.com/embed/reporting/1ldFFV3R1IGJTGG8BwScQhNXD2u7H_4Bh/page/MwXb",
      },
      {
        id: 12,
        name: "Eastwood on Grand",
        link: "https://datastudio.google.com/embed/reporting/1ldFFV3R1IGJTGG8BwScQhNXD2u7H_4Bh/page/MwXb",
      },
      {
        id: 13,
        name: "Gateway Lofts",
        link: "https://datastudio.google.com/embed/reporting/1ldFFV3R1IGJTGG8BwScQhNXD2u7H_4Bh/page/MwXb",
      },
      {
        id: 14,
        name: "Sterling Pointe",
        link: "https://datastudio.google.com/embed/reporting/1ldFFV3R1IGJTGG8BwScQhNXD2u7H_4Bh/page/MwXb",
      },
      {
        id: 15,
        name: "The Villages at Gray's Lake",
        link: "https://datastudio.google.com/embed/reporting/1ldFFV3R1IGJTGG8BwScQhNXD2u7H_4Bh/page/MwXb",
      },
    ],
  },
  {
    id: 2,
    email: "admin2@email.com",
    password: "pass123",
    client: "Aukum Group/Greystar",
    name: [
      "Brookside 112",
      "Cedar House",
      "Adobe Ridge",
      "Cantera",
      "Cityscape at Lakeshore",
      "Ora Apartments",
      "Terra Vista at the Park",
      "The Ridge at Mountain View",
      "Tierra Del Sol",
    ],
  },
  {
    id: 3,
    email: "admin3@email.com",
    password: "pass123",
    client: "Bellevue",
    name: ["Bellevue at Avondale", "Bellevue at the Bluffs"],
  },
  {
    id: 4,
    email: "admin4@email.com",
    password: "pass123",
    client: "BLDG",
    name: ["St. Paul Collection"],
  },
  {
    id: 5,
    email: "admin5@email.com",
    password: "pass123",
    client: "Carter Haston",
    name: [
      "Cobblestone Crossings",
      "Cumberland on Church",
      "Emblem",
      "Gibson at Flowery Branch",
      "Martin Flats",
      "Primrose at Santa Rosa Beach",
      "Solitair Brickell",
      "The Barton",
      "The Crown of Queen City",
      "The Edison Sugarloaf",
      "The Holston Asheville",
      "West End Village",
    ],
  },
  {
    id: 6,
    email: "admin6@email.com",
    password: "pass123",
    client: "Castle Residential",
    name: [
      "1818 Park",
      "Art Square at Hallandale",
      "Bella Vista",
      "Blu on Marina",
      "The Mid Lake Worth Florida",
      "The Six13",
    ],
  },
  {
    id: 7,
    email: "admin7@email.com",
    password: "pass123",
    client: "Crescent",
    name: ["Novel LoSo Station"],
  },
  {
    id: 8,
    email: "admin8@email.com",
    password: "pass123",
    client: "Cushman & Wakefield",
    name: [
      "5 Central",
      "5 Points Apartments",
      "77 Central",
      "Alexan Scottsdale",
      "Alta Mills",
      "Astro Apartments",
      "Audobon Briarcliff",
      "Banyan Kingsland Heights",
      "Beacon Ridge",
      "Bend at Oak Forest",
      "Biltmore Midtown",
      "Boulder Creek",
      "Bridge Creek",
      "Bristol Village",
      "Bull Mountain Heights",
      "Canyon Ridge",
      "Carillon Apartments",
      "Circa Greenlake",
      "Cottage at Wells Branch",
      "Cypress Pointe",
      "Dartford Townhomes",
      "DR Horton (Bridge Harbor/Sunset Village/Parkview at Lynn Haven)",
      "Eagle Pointe",
      "East Heights",
      "East of Eleven",
      "Edgewater on the Lagoon",
      "Ellie Passivhaus",
      "Emerald Lakes South",
      "Enclave at Lake Ellenor",
      "Evo",
      "FIT Apartments",
      "FortyOne 11",
      "Foundry Lake Street",
      "Gulf Stream Townhomes",
      "Helix",
      "Hudson Woodstock",
      "Icaria on Pinellas",
      "Jennings Place",
      "Juno at Winter Park",
      "Kruseway Commons",
      "Laurel West End",
      "LIV at Boerne Hills",
      "LL Hawkins",
      "Lofts at Rose Monte",
      "Luna at Lake Shadow",
      "Metroline Flats",
      "Muse",
      "Octave",
      "Oxbow49",
      "Parkside Crossing",
      "Peachtree Creek on Ponce",
      "Preserve at the Port",
      "Province of Briarcliff",
      "Ravello",
      "Rayette Lofts",
      "Reserves at Pilot Butte Phase 2",
      "Rock Ridge Estates",
      "Sherwood Oaks",
      "Simmons Ridge",
      "Skyline ATL",
      "Society Las Olas",
      "St. Croix",
      "Sygnii",
      "Talo",
      "The Falls at Sope Creek",
      "The Haverly at Stone Mountain",
      "The Hudson at Highline",
      "The Kessler",
      "The Lotus Starkey Ranch",
      "The Morrow",
      "The Nic on Fifth",
      "The Pointe at Cedar Grove",
      "The Ridley",
      "The Village at Union Mills",
      "The Villages of Hickory Street",
      "The Walkway",
      "Thrive at Creekside",
      "Timberline Court",
      "Uptown Lake",
      "Villas at 28th",
      "Viridian at Bonita Springs",
      "Water's Edge",
      "Waterview at Coconut Creek",
      "Webb Bridge Crossing",
      "Williamson at the Overlook",
      "Windermere Trails",
      "Wonderland Creek",
    ],
  },
  {
    id: 9,
    email: "admin9@email.com",
    password: "pass123",
    client: "Cushman & Wakefield/FCP",
    name: [
      "Artisan West",
      "Ashford at Spring Lake",
      "Brookview",
      "Chroma Park",
      "Estuary Apartments",
      "Forest Glen",
      "Hunter's Point",
      "Mableton Ridge",
      "Magnolia Terrace",
      "Meeting Street Lofts",
      "Mirador at Idlewood",
      "Mirador at Peachtree",
      "Monarch Pass",
      "Place at Midway",
      "Reserve at Providence",
      "Somerset",
      "Springdale Glen",
      "Stewarts Mill",
      "Stratford Ridge",
      "The Asher at Sugarloaf",
      "Townsend",
      "Trails of North Hills",
      "Villas at Princeton Lake",
      "Westwood Glen",
      "Wyndcliff at Galleria",
    ],
  },
  {
    id: 10,
    email: "admin10@email.com",
    password: "pass123",
    client: "Cushman & Wakefield/Strata",
    name: [
      "Ashmore Bridge Estates",
      "Aster Place",
      "Audobon Park",
      "Cherrywood Village",
      "One Midtown",
      "Palm Club",
      "Parkside at the Highlands",
      "Patriot Point",
      "Ranchstone",
      "Sage at 1240",
      "The Apartments of St. Charles",
      "The Estates at Quarry Lake",
      "The Gio",
      "The Grove",
      "The Racquet Club",
      "The Retreat at Grande Lake",
      "The Retreat at Hidden Bay",
      "Towne Creek",
      "TownPark Crossing",
      "Verde Vue",
    ],
  },
  {
    id: 11,
    email: "admin11@email.com",
    password: "pass123",
    client: "Cushman Wakefield",
    name: ["The Larking"],
  },
  {
    id: 12,
    email: "admin12@email.com",
    password: "pass123",
    client: "Encore/Greystar",
    name: ["Rise Hayes Valley"],
  },
  {
    id: 13,
    email: "admin13@email.com",
    password: "pass123",
    client: "FCI Residential",
    name: ["Wellington Vista"],
  },
  {
    id: 14,
    email: "admin14@email.com",
    password: "pass123",
    client: "First Communities",
    name: [
      "Ansley Park",
      "Century Belmont Station",
      "Century Dunes",
      "Century Town Center",
      "Vinings RiverVue",
    ],
  },
  {
    id: 15,
    email: "admin15@email.com",
    password: "pass123",
    client: "FLF Management",
    name: ["Lilac Village Boca Raton", "View Carlton Arms"],
  },
  {
    id: 16,
    email: "admin16@email.com",
    password: "pass123",
    client: "Flournoy",
    name: [
      "35 Folly",
      "Amberleigh South",
      "Aventine Asheville",
      "Aventine West Melbourne",
      "Rock Island Ridges",
      "Sea Sound",
    ],
  },
  {
    id: 17,
    email: "admin17@email.com",
    password: "pass123",
    client: "FPI",
    name: ["The Eisley"],
  },
  {
    id: 18,
    email: "admin18@email.com",
    password: "pass123",
    client: "FPI Management",
    name: ["Fremont Mews", "H16 Midtown Apartments", "The Eleanor"],
  },
  {
    id: 19,
    email: "admin19@email.com",
    password: "pass123",
    client: "Greystar",
    name: ["The Reserve at the Plaza", "The Rise Hollywood"],
  },
  {
    id: 20,
    email: "admin20@email.com",
    password: "pass123",
    client: "Lincoln",
    name: [
      "Russell Reston Station",
      "Siena Park",
      "The Blake",
      "The Earl",
      "The Ellington",
    ],
  },
  {
    id: 21,
    email: "admin21@email.com",
    password: "pass123",
    client: "Peak Made",
    name: ["The Overlook at St. Gabriel's"],
  },
  {
    id: 22,
    email: "admin22@email.com",
    password: "pass123",
    client: "RangeWater",
    name: [
      "Anker Haus",
      "Aria Bradenton",
      "Bungalow Oaks",
      "Bungalows on Estrella",
      "Cabana Power",
      "Capstone at Banks Crossing",
      "City Vista",
      "Emery Place",
      "Independence Park",
      "Isle Cottages",
      "Linc Brookhaven",
      "Palmview Cove",
      "Parkway Square",
      "Tally Square",
      "The Overlook at Buffalo Park",
      "The Residences at 393",
      "Trellis at the Lakes",
      "Walker Steele Creek",
      "Wynwood Bay",
    ],
  },
  {
    id: 23,
    email: "admin23@email.com",
    password: "pass123",
    client: "RangeWater/Encore",
    name: ["The Rise Flagler Village"],
  },
  {
    id: 24,
    email: "admin24@email.com",
    password: "pass123",
    client: "Rentyl/Encore",
    name: ["Sentosa at Riverview"],
  },
  {
    id: 25,
    email: "admin25@email.com",
    password: "pass123",
    client: "Stonemark",
    name: [
      "Madison Park",
      "Midsouth 301",
      "Spring Lake",
      "The Park at Moss Creek",
      "The Rey on Reynolds",
      "Van Mark",
      "Windsor Lake",
    ],
  },
];

export const accounts = [
  {
    id: 1,
    email: "admin1@email.com",
    password: "pass123",
    name: "Artisan",
  },
  {
    id: 2,
    email: "admin2@email.com",
    password: "pass123",
    name: "Aukum Group/Greystar",
  },
  {
    id: 3,
    email: "admin3@email.com",
    password: "pass123",
    name: "Bellevue",
  },
  {
    id: 4,
    email: "admin4@email.com",
    password: "pass123",
    name: "BLDG",
  },
  {
    id: 5,
    email: "admin5@email.com",
    password: "pass123",
    name: "Carter Haston",
  },
  {
    id: 6,
    email: "admin6@email.com",
    password: "pass123",
    name: "Castle Residential",
  },
  {
    id: 7,
    email: "admin7@email.com",
    password: "pass123",
    name: "Crescent",
  },
  {
    id: 8,
    email: "admin8@email.com",
    password: "pass123",
    name: "Cushman & Wakefield",
  },
  {
    id: 9,
    email: "admin9@email.com",
    password: "pass123",
    name: "Cushman & Wakefield/FCP",
  },
  {
    id: 10,
    email: "admin10@email.com",
    password: "pass123",
    name: "Cushman & Wakefield/Strata",
  },
  {
    id: 11,
    email: "admin11@email.com",
    password: "pass123",
    name: "Cushman Wakefield",
  },
  {
    id: 12,
    email: "admin12@email.com",
    password: "pass123",
    name: "Encore/Greystar",
  },
  {
    id: 13,
    email: "admin13@email.com",
    password: "pass123",
    name: "FCI Residential",
  },
  {
    id: 14,
    email: "admin14@email.com",
    password: "pass123",
    name: "First Communities",
  },
  {
    id: 15,
    email: "admin15@email.com",
    password: "pass123",
    name: "FLF Management",
  },
  {
    id: 16,
    email: "admin16@email.com",
    password: "pass123",
    name: "Flournoy",
  },
  {
    id: 17,
    email: "admin17@email.com",
    password: "pass123",
    name: "FPI",
  },
  {
    id: 18,
    email: "admin18@email.com",
    password: "pass123",
    name: "FPI Management",
  },
  {
    id: 19,
    email: "admin19@email.com",
    password: "pass123",
    name: "Greystar",
  },
  {
    id: 20,
    email: "admin20@email.com",
    password: "pass123",
    name: "Lincoln",
  },
  {
    id: 21,
    email: "admin21@email.com",
    password: "pass123",
    name: "Peak Made",
  },
  {
    id: 22,
    email: "admin22@email.com",
    password: "pass123",
    name: "RangeWater",
  },
  {
    id: 23,
    email: "admin23@email.com",
    password: "pass123",
    name: "RangeWater/Encore",
  },
  {
    id: 24,
    email: "admin24@email.com",
    password: "pass123",
    name: "Rentyl/Encore",
  },
  {
    id: 25,
    email: "admin25@email.com",
    password: "pass123",
    name: "Stonemark",
  },
];
